# Generated by Django 5.0.4 on 2024-07-25 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Pfile',
            new_name='pfile',
        ),
    ]
